# Generated by Django 5.2.8 on 2025-11-26 20:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El serial debe tener exactamente 12 caracteres:letras numeros', regex='^[A-Za-z0-9#_@%$]{12}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('fecha_compra', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('valor', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones_sensor', to='aplicacion.sensor')),
            ],
        ),
    ]
