# Generated by Django 5.2.8 on 2025-12-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='valor',
        ),
    ]
