# Generated by Django 5.2.8 on 2025-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_medicion_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='medicion',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
